name: Docker Image CI
# on:
#   push:
#     branches:
#       - main
#     paths-ignore:
#       - '**/README.md'
on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: number
      port:
        required: true
        type: number
      table:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          PORT: ${{ inputs.port }}
          TABLE: ${{ inputs.table }}
        run: |
          IMAGE_TAG=$${{ inputs.build_id }}
          docker build --build-arg table=$TABLE --build-arg port=$PORT -t dpnodeapp:$IMAGE_TAG .
      - name: Push to DockerHub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker tag dpnodeapp:$IMAGE_TAG $DOCKER_USER/dp-repository:$IMAGE_TAG
          docker push $DOCKER_USER/dp-repository:$IMAGE_TAG
